[tool.black]
line-length = 80
include = '\.pyi?$'
preview = true
skip-string-normalization = true
experimental-string-processing = true
extend-exclude = '''
/(
  | .git
  | .env
)/
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]